name: CI Pipeline
on: [push]

jobs:
  build:
    name: Run unit and integration tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build and test application
        run: ./gradlew build
