name: CD Pipeline
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Compile and test application
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Package as a container image
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage
      - name: Push container image to Docker Hub
        run: docker push polarbookshop/order-service:0.0.1-SNAPSHOT
