apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: polar-rabbitmq
  namespace: rabbitmq-system
spec:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 275Mi
    limits:
      cpu: 250m
      memory: 275Mi
  persistence:
    storage: 1Gi
  rabbitmq:
    additionalConfig: |
      vm_memory_high_watermark_paging_ratio = 0.99
      vm_memory_high_watermark.relative = 0.90
  terminationGracePeriodSeconds: 60
