name: CI Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build and test application
        run: |
          chmod +x gradlew
          ./gradlew build
  package:
    name: Package and Publish Image
    needs: [build]
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Containerize
        run: |
          chmod +x gradlew
          ./gradlew bootBuildImage
      - name: Push to Docker Hub
        run: docker push polarbookshop/order-service:0.0.1-SNAPSHOT
