apiVersion: skaffold/v2beta12
kind: Config
metadata:
  name: dispatcher-service
build:
  artifacts:
    - image: polarbookshop/dispatcher-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
deploy:
  helm:
    releases:
      - name: polarmq-broker
        chartPath: bitnami/rabbitmq
        remote: true
        setValues:
          auth.username: user
          auth.password: password
          image.tag: 3.8
          service.port: 5672
          service.managerPort: 15672
  kubectl:
    manifests:
      - k8s/*.yml
