loki:
  enabled: true
  image:
    tag: 2.6.1
  config:
    ingester:
      wal:
        dir: /data/loki/wal

promtail:
  enabled: false
  image:
    tag: 2.6.1

fluent-bit:
  enabled: true
  image:
    tag: 2.6.1-amd64

grafana:
  enabled: true
  image:
    tag: 9.1.2
  adminUser: heimdall
  service:
    type: ClusterIP
  sidecar:
    dashboards:
      enabled: true
      provider:
        allowUiUpdates: true
    datasources:
      enabled: false
  datasources:
    "datasources.yaml":
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          uid: prometheus-thomas-vitale
          access: proxy
          orgId: 1
          url: http://loki-stack-prometheus-server
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
        - name: Tempo
          type: tempo
          uid: tempo-thomas-vitale
          access: proxy
          orgId: 1
          url: http://tempo:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: true
          jsonData:
            httpMethod: GET
            tracesToLogs:
              datasourceUid: 'loki-thomas-vitale'
              tags: [ 'instance', 'pod', 'namespace', 'hostname' ]
              mappedTags: [ { key: 'service.name', value: 'application' } ]
              mapTagNamesEnabled: true
              spanStartTimeShift: '1h'
              spanEndTimeShift: '1h'
              filterByTraceID: true
              filterBySpanID: false
              lokiSearch: true
            serviceMap:
              datasourceUid: 'prometheus-thomas-vitale'
            search:
              hide: false
            nodeGraph:
              enabled: true
        - name: Loki
          type: loki
          uid: loki-thomas-vitale
          access: proxy
          orgId: 1
          url: http://loki-stack:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: true
          jsonData:
            derivedFields:
              - datasourceUid: tempo-thomas-vitale
                matcherRegex: \d+\-\d+\-\d+ \d+\:\d+\:\d+\.\d+\s+\w+\s+\[[\w-]+\,(\w+)\,\w+\]
                name: TraceID
                url: $${__value.raw}

prometheus:
  enabled: true
  alertmanager:
    enabled: false
  configmapReload:
    alertmanager:
      enabled: false
  kubeStateMetrics:
    metricLabelsAllowlist:
      - pods=[*]
      - deployments=[app.kubernetes.io/name,app.kubernetes.io/component,app.kubernetes.io/instance]
  pushgateway:
    enabled: false
  server:
    global:
      scrape_interval: 15s
    image:
      tag: v2.38.0
    persistentVolume:
      enabled: false
