apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-service
spec:
  template:
    spec:
      containers:
        - name: catalog-service
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-javaagent:/workspace/BOOT-INF/lib/opentelemetry-javaagent-1.24.0.jar"
            - name: OTEL_SERVICE_NAME
              value: catalog-service
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://tempo.observability-stack.svc.cluster.local:4317
            - name: OTEL_METRICS_EXPORTER
              value: none
