apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - namespace.yml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.4.15/manifests/install.yaml

patchesStrategicMerge:
  - patch-service.yml
