apiVersion: skaffold/v2beta17
kind: Config
metadata:
  name: order-service
build:
  artifacts:
    - image: polarbookshop/order-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=11.*
deploy:
  helm:
    releases:
      - name: polar-postgres-order
        remoteChart: bitnami/postgresql
        setValues:
          postgresqlUsername: admin
          postgresqlPassword: admin
          postgresqlDatabase: polardb_order
          image.tag: 13
          service.port: 5433
  kubectl:
    manifests:
      - k8s/*.yml
