spring:
  config:
    import: optional:configserver:,configtree:/workspace/secrets/*/
  cloud:
    config:
      uri: http://config-service
  flyway:
    url: jdbc:postgresql://polar-postgres-order/polardb_order
  r2dbc:
    url: r2dbc:postgresql://polar-postgres-order/polardb_order
  rabbitmq:
    host: polar-rabbitmq

polar:
  catalog-service-url: http://catalog-service