{
 "title": "Spring Cloud Gateway",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "gatewayService",
    "label": "Gateway Service",
    "query": {
     "query": "label_values(spring_cloud_gateway_requests_seconds_count,job)"
    }
   },
   {
    "name": "routeId",
    "label": "Route Id",
    "query": {
     "query": "label_values(spring_cloud_gateway_requests_seconds_count,routeId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests Served",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spring_cloud_gateway_requests_seconds_count{job=~\"$gatewayService\"})"
      }
     ]
    },
    {
     "title": "Total Successful Requests Served",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", job=~\"$gatewayService\"})"
      }
     ]
    },
    {
     "title": "Total Unsuccessful Requests Served",
     "type": "stat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", job=~\"$gatewayService\"})"
      }
     ]
    }
   ]
  },
  { "title": "Request Processing Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_sum{routeId=~\"$routeId\", job=~\"$gatewayService\"}/spring_cloud_gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  { "title": "Successful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "$routeId Success API Gateway Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  { "title": "Unsuccessful API Calls", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "$routeId Unsuccessful GW Calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spring_cloud_gateway_requests_seconds_count{outcome!=\"SUCCESSFUL\", routeId=~\"$routeId\", job=~\"$gatewayService\"}",
     "legendFormat": "{{ job }} / {{ routeUri }}"
    }
   ]
  },
  { "title": "API / HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "$routeId",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "repeat": "routeId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spring_cloud_gateway_requests_seconds_count{routeId=~\"$routeId\", job=~\"$gatewayService\"}) by (job, status)",
     "legendFormat": "{{ job }} / {{ status }}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_usage{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=~\"$gatewayService\"}) by (job, instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Live Threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_live_threads{job=~\"$gatewayService\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Memory Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_promoted_bytes_total/jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}