version: "3.8"
services:

  # Applications

  catalog-service:
    depends_on:
      - polar-keycloak
      - polar-postgres-catalog
    image: "<your_dockerhub_username>/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 8001
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8001
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polar-postgres-catalog:5432/polardb_catalog
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  
  order-service:
    depends_on:
      - polar-keycloak
      - polar-postgres-order
      - polar-rabbitmq
    image: "<your_dockerhub_username>/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8002
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - POLAR_CATALOG_SERVICE_URL=http://catalog-service:9001
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_R2DBC_URL=r2dbc:postgresql://polar-postgres-order:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polar-postgres-order:5432/polardb_order
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  
  dispatcher-service:
    depends_on:
      - polar-rabbitmq
    image: "<your_dockerhub_username>/dispatcher-service:0.0.1-SNAPSHOT"
    container_name: dispatcher-service
    ports:
      - 9003:9003
      - 8003:8003
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8002
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8003
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  
  edge-service:
    depends_on:
      - polar-keycloak
      - polar-redis
    image: "<your_dockerhub_username>/edge-service:0.0.1-SNAPSHOT"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # Buildpacks environment variable to enable debug through a socket on port 8000
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - KEYCLOAK_URL=http://host.docker.internal:8080
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_CLOUD_CONFIG_URI=http://config-service:8888
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
      - SPRING_REDIS_HOST=polar-redis
  
  config-service:
    image: "<your_dockerhub_username>/config-service:0.0.1-SNAPSHOT"
    container_name: "config-service"
    ports:
      - 8888:8888
      - 9888:9888
    environment:
      # Buildpacks environment variable to configure the number of threads in memory calculation
      - BPL_JVM_THREAD_COUNT=50
      # Buildpacks environment variable to enable debug through a socket on port 9888
      - BPL_DEBUG_ENABLED=true
      - BPL_DEBUG_PORT=9888
      - ENCRYPT_KEY=sharedkey
      - SPRING_RABBITMQ_HOST=polar-rabbitmq
  
  # Backing Services

  polar-postgres-catalog:
    image: "postgres:13.4"
    container_name: "polar-postgres-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_catalog

  polar-postgres-order:
    image: "postgres:13.4"
    container_name: "polar-postgres-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polardb_order

  polar-redis:
    image: "redis:6.2"
    container_name: "polar-redis"
    ports:
      - 6379:6379
  
  polar-rabbitmq:
    image: rabbitmq:3.8-management
    container_name: polar-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  
  polar-keycloak:
    image: jboss/keycloak:15.0.1
    container_name: "polar-keycloak"
    volumes:
      - ./keycloak:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_USER: user
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/full-realm-export.json
    ports:
      - 8080:8080
