apiVersion: v1
kind: Service
metadata:
  name: dispatcher-service
  labels:
    app: dispatcher-app
spec:
  type: ClusterIP
  selector:
    app: dispatcher-app
  ports:
  - protocol: TCP
    port: 9003
    targetPort: 9003
