apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: order-service
build:
  artifacts:
    - image: polarbookshop/order-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=17.*
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
