server:
  port: 9002
  netty:
    connection-timeout: 5s
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 15s
  r2dbc:
    username: admin
    password: admin
    url: r2dbc:postgresql://localhost:5433/polardb_order
    pool:
      max-create-connection-time: 5s
      initial-size: 5
      max-size: 10
  flyway:
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    url: jdbc:postgresql://localhost:5433/polardb_order
  cloud:
    function:
      definition: acceptOrder;dispatchOrder
    stream:
      bindings:
        dispatchOrder-in-0:
          destination: order-dispatched
          group: polar-updater
        acceptOrder-out-0:
          destination: order-accepted
      rabbit:
        bindings:
          order-accepted:
            producer:
              transacted: true
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: password
    connection-timeout: 15s
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/auth/realms/PolarBookshop

logging.level.reactor.core.*: debug

polar:
  catalog-service-url: "http://localhost:9001/books/"
