apiVersion: v1
kind: Service
metadata:
  name: config-service
  labels:
    app: config-app
spec:
  type: ClusterIP
  selector:
    app: config-app
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
