apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/polarbookshop/dispatcher-service/k8s?ref=main

patchesStrategicMerge:
  - patch-env.yml

configMapGenerator:
  - behavior: merge
    files:
      - application-staging.yml
    name: dispatcher-config

images:
  - name: dispatcher-service
    newName: ghcr.io/polarbookshop/dispatcher-service
    newTag: latest

replicas:
  - name: dispatcher-service
    count: 1
