apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher-service
  template:
    spec:
      containers:
        - name: dispatcher-service
          image: polarbookshop/dispatcher-service:0.0.1-SNAPSHOT
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9003
          volumeMounts:
            - name: dispatcher-service-volume
              mountPath: /workspace/config
            - name: dispatcher-service-volume-secret
              mountPath: /workspace/secrets/dispatcher-service-secret
      volumes:
        - name: dispatcher-service-volume
          configMap:
            name: dispatcher-service
        - name: dispatcher-service-volume-secret
          secret:
            secretName: dispatcher-service
