version: "3.8"
services:
  polardb-catalog:
    image: "postgres:13"
    container_name: "polardb-catalog"
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_catalog
  catalog-service:
    image: "polarbookshop/catalog-service:0.0.1-SNAPSHOT"
    container_name: "catalog-service"
    ports:
      - 9001:9001
      - 8001:8001
    environment:
      # JVM environment variable to enable debug through a socket on port 8001
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8001
      - SPRING_DATASOURCE_URL=jdbc:postgresql://polardb-catalog:5432/polardb_catalog

  polardb-order:
    image: "postgres:13"
    container_name: "polardb-order"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=polardb_order
  order-service:
    depends_on:
      - polardb-order
    image: "polarbookshop/order-service:0.0.1-SNAPSHOT"
    container_name: "order-service"
    ports:
      - 9002:9002
      - 8002:8002
    environment:
      # JVM environment variable to enable debug through a socket on port 8002
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8002
      - POLAR_CATALOG_SERVICE_URL=http://catalog-service:9001/books/
      - SPRING_R2DBC_URL=r2dbc:postgresql://polardb-order:5432/polardb_order
      - SPRING_FLYWAY_URL=jdbc:postgresql://polardb-order:5432/polardb_order
      - SPRING_RABBITMQ_HOST=polarmq-broker

  polardb-redis:
    image: "redis:6"
    container_name: "polardb-redis"
    ports:
      - 6379:6379
  edge-service:
    image: "polarbookshop/edge-service:0.0.1-SNAPSHOT"
    container_name: "edge-service"
    ports:
      - 9000:9000
      - 8000:8000
    environment:
      # JVM environment variable to enable debug through a socket on port 8000
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
      - CATALOG_SERVICE_URL=http://catalog-service:9001
      - ORDER_SERVICE_URL=http://order-service:9002
      - SPRING_REDIS_HOST=polardb-redis
  
  polarmq-broker:
    image: rabbitmq:3-management
    container_name: polarmq-broker
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password
  dispatcher-service:
    image: polarbookshop/dispatcher-service:0.0.1-SNAPSHOT
    container_name: dispatcher-service
    ports:
      - 8003:8003
    environment:
      # JVM environment variable to enable debug through a socket on port 8003
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8003
      - SPRING_RABBITMQ_HOST=polarmq-broker
  
  polardb-keycloak:
    image: "postgres:13"
    container_name: "polardb-keycloak"
    ports:
      - 5434:5434
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:12.0.4
    container_name: "keycloak"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: polardb-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_SCHEMA: public
      DB_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - 8181:8080
