apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-app
spec:
  type: ClusterIP
  selector:
    app: catalog-app
  ports:
  - protocol: TCP
    port: 9001
    targetPort: 9001
