apiVersion: skaffold/v2beta23
kind: Config
metadata:
  name: order-service
build:
  artifacts:
    - image: polarbookshop/order-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=17.*
deploy:
  kustomize:
    paths:
      - k8s
