apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: config-service
build:
  artifacts:
    - image: polarbookshop/config-service
      buildpacks:
        builder: gcr.io/paketo-buildpacks/builder:base
        env:
          - BP_JVM_VERSION=17.*
deploy:
  kubectl:
    manifests:
      - k8s/*.yml
