name: Commit Stage
on:
  push:
  schedule: # Every Monday
    - cron: '0 0 * * 1'

jobs:
  build:
    name: Build and Test ${{ matrix.project }}
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        project: [
          Chapter02/02-end/catalog-service,
          Chapter03/03-end/catalog-service,
          Chapter04/04-end/catalog-service,
          Chapter04/04-end/config-service,
          Chapter05/05-intermediate/catalog-service,
          Chapter05/05-end/catalog-service,
          Chapter05/05-end/catalog-service-jpa,
          Chapter05/05-end/config-service,
          Chapter06/06-end/catalog-service,
          Chapter06/06-end/config-service,
          Chapter07/07-end/catalog-service,
          Chapter07/07-end/config-service,
          Chapter08/08-end/catalog-service,
          Chapter08/08-end/config-service,
          Chapter08/08-end/order-service,
          Chapter09/09-end/catalog-service,
          Chapter09/09-end/config-service,
          Chapter09/09-end/edge-service,
          Chapter09/09-end/order-service,
          Chapter10/10-intermediate/dispatcher-service,
          Chapter10/10-end/catalog-service,
          Chapter10/10-end/config-service,
          Chapter10/10-end/order-service,
          Chapter10/10-end/edge-service,
          Chapter10/10-end/dispatcher-service,
          Chapter11/11-end/catalog-service,
          Chapter11/11-end/config-service,
          Chapter11/11-end/order-service,
          Chapter11/11-end/edge-service,
          Chapter11/11-end/dispatcher-service,
          Chapter12/12-end/catalog-service,
          Chapter12/12-end/config-service,
          Chapter12/12-end/order-service,
          Chapter12/12-end/edge-service,
          Chapter12/12-end/dispatcher-service,
          Chapter13/13-end/catalog-service,
          Chapter13/13-end/config-service,
          Chapter13/13-end/order-service,
          Chapter13/13-end/edge-service,
          Chapter13/13-end/dispatcher-service,
          Chapter14/14-end/catalog-service,
          Chapter14/14-end/config-service,
          Chapter14/14-end/order-service,
          Chapter14/14-end/edge-service,
          Chapter14/14-end/dispatcher-service,
          Chapter15/15-end/catalog-service,
          Chapter15/15-end/config-service,
          Chapter15/15-end/order-service,
          Chapter15/15-end/edge-service,
          Chapter15/15-end/dispatcher-service,
          Chapter16/16-end/quote-service,
          Chapter16/16-end/quote-function,
        ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - name: Build, unit tests and integration tests
        run: |
          cd ${{ matrix.project }}
          chmod +x gradlew
          ./gradlew build
